version: "3.8"

x-common-service-settings: &common_service_settings
  env_file: .env
  tty: true
  network_mode: "host"
  working_dir: "${PWD}"
  build: &common_build_settings
    context: .
    args: &common_build_args
      UID: ${UID:-1000}
      ADDITIONAL_GROUPS: ""
      NODE_VERSION: "${NODE_VERSION:-14.10.1}"
      YARN_VERSION: "${YARN_VERSION:-1.22.5}"
      PARALLEL_LEVEL: "${PARALLEL_LEVEL:-}"
      CMAKE_VERSION: "${CMAKE_VERSION:-3.18.5}"
      CCACHE_VERSION: "${CCACHE_VERSION:-4.1}"
  environment: &common_environment_variables
    # Colorize the terminal in the container if possible
    TERM: "${TERM:-}"
    # Use the host's X11 display
    DISPLAY: "${DISPLAY:-}"
    XAUTHORITY: "${XAUTHORITY:-}"
    XDG_SESSION_TYPE: "${XDG_SESSION_TYPE:-}"
    NVIDIA_DRIVER_CAPABILITIES: "all"

services:

  runtime:
    <<: *common_service_settings
    image: rapidsai/js:${RAPIDS_VERSION:-latest}-cuda${CUDA_VERSION:-11.0}-runtime-${LINUX_VERSION:-ubuntu18.04}-amd64
    build:
      <<: *common_build_settings
      dockerfile: dockerfiles/runtime.Dockerfile
      args:
        <<: *common_build_args
        CUDA_BASE_IMAGE: nvidia/cudagl:${CUDA_VERSION:-11.0}-runtime-${LINUX_VERSION:-ubuntu18.04}
    volumes:
      - &workdir "${PWD}:${PWD}:rw"
      - &etc_fonts "/etc/fonts:/etc/fonts:ro"
      - &x11_socket "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - &usr_share_fonts "/usr/share/fonts:/usr/share/fonts:ro"
      - &usr_share_icons "/usr/share/icons:/usr/share/icons:ro"

  devel:
    <<: *common_service_settings
    image: rapidsai/js:${RAPIDS_VERSION:-latest}-cuda${CUDA_VERSION:-11.0}-devel-${LINUX_VERSION:-ubuntu18.04}-amd64
    build:
      <<: *common_build_settings
      dockerfile: dockerfiles/devel.Dockerfile
      args:
        <<: *common_build_args
        ADDITIONAL_GROUPS: "--groups sudo"
        CUDA_BASE_IMAGE: nvidia/cudagl:${CUDA_VERSION:-11.0}-devel-${LINUX_VERSION:-ubuntu18.04}
    volumes:
      - *workdir
      - *etc_fonts
      - *x11_socket
      - *usr_share_fonts
      - *usr_share_icons
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE

  # Services for Jetson Xavier AGX

  runtime-arm64v8:
    <<: *common_service_settings
    image: rapidsai/js:${RAPIDS_VERSION:-latest}-cuda10.2-runtime-ubuntu18.04-arm64v8
    build:
      <<: *common_build_settings
      dockerfile: dockerfiles/runtime.Dockerfile
      args:
        <<: *common_build_args
        ADDITIONAL_GROUPS: "--groups video"
        CUDA_BASE_IMAGE: nvcr.io/nvidia/l4t-base:r32.4.4
    volumes:
      - *workdir
      - *etc_fonts
      - *x11_socket
      - *usr_share_fonts
      - *usr_share_icons

  devel-arm64v8:
    <<: *common_service_settings
    image: rapidsai/js:${RAPIDS_VERSION:-latest}-cuda10.2-devel-ubuntu18.04-arm64v8
    build:
      <<: *common_build_settings
      dockerfile: dockerfiles/devel.Dockerfile
      args:
        <<: *common_build_args
        ADDITIONAL_GROUPS: "--groups sudo,video"
        CUDA_BASE_IMAGE: nvcr.io/nvidia/l4t-base:r32.4.4
    volumes:
      - *workdir
      - *etc_fonts
      - *x11_socket
      - *usr_share_fonts
      - *usr_share_icons
    environment:
      <<: *common_environment_variables
      # Build for CUDA architecture sm_72
      CUDAARCHS: "72-real"
      JOBS: 2
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
